### ISSUE TITLE
reversible reaction 

### ISSUE THREAD

**Issue by metma99** [SciML/Catalyst.jl#198]
Quick question if I may:
I tried to use <>, <->, and <--> for representing reversible reactions without success. Errors are ">" is not a unary operator, invalid identifier name "->".
Because of technical reasons I cannot use the double arrow used in the examples.
Is the double arrow in the examples the only way to represent equilibrium reactions?
Markus

**Comment by TorkelE** [comment]
This basically has to do with the parsing of expressions in Julia. When creating expressions I think neither one of 
```julia
rxn = @reaction_network begin
2.0, X + Y <--> XY
2.0, X + Y <-> XY
2.0, X + Y <> XY
end
``` 
yields working code. Similar limitations for how expressions are parsed makes it so we cannot use `X + Y -> XY`, but have to use `X + Y --> XY`.

This leaves us with only various one character symbols as possible separators for reversible reactions (`↔, ⟷, ⇄, ⇆, ⇔, ⟺` added currently). If someone came up with a way of using `<-->, <->, <>` that would be good. But I simply don't think this is possible, given the current way expressions work in julia.

For your problem specifically, it would be interesting to know why you cannot use those arrows? And what alternative symbols you have available? More practically, what you will have to do here, is to simply write out both reactions:

```julia
rxn = @reaction_network begin
2.0, X + Y --> XY
2.0, XY --> X + Y
end
```

**Comment by ChrisRackauckas** [comment]
>This leaves us with only various one character symbols as possible separators for reversible reactions (↔, ⟷, ⇄, ⇆, ⇔, ⟺ added currently). If someone came up with a way of using <-->, <->, <> that would be good. But I simply don't think this is possible, given the current way expressions work in julia.

Some of the arrows parse in the parser, like -->. I thought bidirectional arrows were in the list?

**Comment by TorkelE** [comment]
`-->` is the only exception we have currently. Basically everything that is just counted as a symbol makes
`X ... Y` and vector with the elements `X`, `...` and `Y`. Here `...` can be one of all the different arrows we have added to our list (`⟷`, etc.).

I'm not really sure what kind of operation `-->` is, but `X --> Y` is a valid expression, and since it is a natural way to write things we have a special check to parse this. If you, however, try to write something like 
```
ex = :(X <> Y)
ex = :(X <-> Y)
ex = :(X <--> Y)
```
you will get an error (`syntax: invalid identifier name "->"`), so we cannot even create some kind of exception to handle them specifically. I think these are interpreted as `X`, followed by a `<`, followed by a `>`, or `->`, or `-->`, and Julia don't know how to make sense of that.

**Comment by isaacsas** [comment]
@metma99 So Julia will add the ability to parse reversible reaction arrows, which in turn will (eventually) allow us to user them here. I assume this won't be available until at least 1.6 though. See https://github.com/JuliaLang/julia/issues/36666

**Comment by metma99** [comment]
Thank you very much!

**Comment by isaacsas** [comment]
This works now with version 6.11 and Julia 1.6!
