### ISSUE TITLE
Use Catlab through import only, or just reimplement basic Graph code

### ISSUE THREAD

**Issue by isaacsas** [SciML/Catalyst.jl#250]
Currently I'm getting errors about both ModelingToolkit and Catlab exporting `Expression`.

Catlab is a relatively heavy dependency (though MT is heavier), so it might make sense to just copy over the limited Graphviz functionality/definitions we need (it isn't much).

**Comment by ChrisRackauckas** [comment]
I would think it would make the most sense to have a Graphviz.jl that both take in. @jpfairbanks

**Comment by jpfairbanks** [comment]
Can’t you do `import Catlab` and import only what you need to fix that specific problem? 

We are planning in the medium run to have a version of the GraphViz.Graph data structure, which should be a strongly typed Property Graph supporting loops, and multi edges, built on top of the Catlab.CategoricalAlgebra.CSet implementation. This will give us the ability to check that all the properties are valid in Julia rather than just creating a list of Graphviz statements and hoping that the user did it right. And this will give us a hierarchical language for specifying graph visualizations in terms of subgraph visualizations. I think that will be very powerful once implemented. So I don’t think we want to rush to fully decouple the GraphViz and Catlab codebases. @epatters might think differently about that. 

There is probably a way to get the current functionality without Catlab, but that is trending in the opposite direction of our long term vision, where we use Catlab data structures (namely CSet) for more of the functionality.

**Comment by ChrisRackauckas** [comment]
Since Catalyst isn't using the actual Catlab pieces here though, I think a package which just sets up the jll and has a bit of plotting code can still be useful (even for LightGraphs), even if Catlab heavily extends it.

**Comment by epatters** [comment]
Usually when I use the `Graphviz` module, I just import it, so write `Graphviz.Node`, `Graphviz.Edge`, etc.

Another solution would be to rename `Expression` to `GraphvizExpr` or something similar. I'd be fine with that, and it wouldn't break much code because it's just the abstract base type used internally.

**Comment by isaacsas** [comment]
Switched to importing in https://github.com/SciML/Catalyst.jl/pull/251. When https://github.com/JuliaPackaging/Yggdrasil/issues/1428 gets resolved we can switch to the jll look into switching to a direct wrapper around it.
