### ISSUE TITLE
WARNING: both Catalyst and Flux export "params"; uses of it in module Main must be qualified

### ISSUE THREAD

**Issue by yewalenikhil65** [SciML/Catalyst.jl#260]
Hello,
The API function `params()` in Catalyst appears to invokes a warning when using with Flux , as Flux also has `Flux.params()` . Also it might create some confusion when  needed to use these packages together.. Is there any work-around or can params in Catalyst be re-named? 
![image](https://user-images.githubusercontent.com/26343789/94011636-4cf91b80-fdc5-11ea-8491-41c3d06e0e22.png)

**Comment by isaacsas** [comment]
You just need to explicitly qualify the module, i.e.: `Catalyst.params(rn)` or `Flux.params(...)`.

Unfortunately, the more packages one loads the more likely a name clash is to occur. Maybe you can mitigate this by only importing the specific commands you need to use instead of `using` both packages?

**Comment by ChrisRackauckas** [comment]
We definitely shouldn't export params though: this is going to be way too common.

**Comment by isaacsas** [comment]
It's been part of the API for several years. Wouldn't the same arguments say that MT shouldn't export `parameters`?

**Comment by ChrisRackauckas** [comment]
What library does that overlap with?

**Comment by yewalenikhil65** [comment]
I didn't knew about `Catalyst.parameters()` in `Catalyst` which does same work as `Catalyst.params()`

Atleast `parameters`, this is good work around when using with Flux I suppose.

**Comment by isaacsas** [comment]
I mean `parameters` is just as generic a name; it's hard to imagine it won't get reused (if it isn't already) by some other library. I'm not sure if every time some other library chooses to add a method with the same name we should break the API to avoid warnings. 

If this is really a big deal, perhaps it suggests the need for a common `Parameters` package that defines such methods and can be extended by Catalyst, Flux, etc.

**Comment by yewalenikhil65** [comment]
I agree with @isaacsas , or else I suggest that we could specifically say `params` as `rates` for `catalyst` as it sounds more chemical name ?

**Comment by TorkelE** [comment]
The problem with `rates` is that it only works for constant rates, but if you have a reaction driven by a hill function then the reaction rate consists of several parameters.

On a more general curiosity note, is there some reason Julia cannot handle (or chose not to handle) identical functions from several packages? With multiple dispatches, since these typically act on package unique objects, there should be no doubt of which `parameters()` function the user intends to use?

**Comment by isaacsas** [comment]
@TorkelE I had the same question, see this thread https://discourse.julialang.org/t/function-name-conflict-adl-function-merging/10335/4

It seems like the merits of allowing two function definitions if they don't overlap has been heavily discussed from the links there... 

The only real solution as far as I can see, beyond restricting to importing or qualifying the name, is to have a common package that defines a base function everyone then creates dispatches from.

**Comment by TorkelE** [comment]
Happy to know this has been thought through. A common package might be handy, but also feels like a cranky solution. For now, qualifying names is not that bad, I already do that quite often.

**Comment by isaacsas** [comment]
We’ve depreciated `params` so this should go away in a future release.
