### ISSUE TITLE
Reaction expression parser

### ISSUE THREAD

**Issue by thevolatilebit** [SciML/Catalyst.jl#330]
It'd be nice to isolate the reaction expression parser for use in, e.g., loading reactions from a file. This is simple to do: One can overload `get_reactions` as in `get_reactions(exs::Vector{Expr}, reactions = Vector{ReactionStruct}(undef,0))` (where the `exs` are the reaction expressions as supplied in `@reaction_network`.).

I'd be grateful to know if there's a more generic / elegant approach / you've some ideas on this that I'd implement and push.

**Comment by isaacsas** [comment]
If you want to put in a PR that makes the parsing code more modular that would be great and appreciated! It would need some work to generate `Reaction`s  from one reaction line I think since the parser needs to know and define parameter and species variables too before making a reaction.

You could always also just build a string with the macro wrapping the reactions, and then `eval` it. While that’s not recommended for loading other people’s code it would be fine for your own files.

**Comment by Leticia-maria** [comment]
Could I submit a PR for it? I did something that would fit.

**Comment by isaacsas** [comment]
Certainly! Making it more modular would be great. We've also recently discussed adding a 
```julia
rx = @reaction k, A --> B
```
type macro, so having a standalone parser for such expressions would be good. The plan was to make it default to having `k` be a parameter and anything in the reaction part (i.e. `A --> B`) be a species, with users being able to override this default behavior by predeclaring a symbol with ModelingToolkit's `@parameters` and `@variables` macros.

**Comment by isaacsas** [comment]
We support serialization now, so I think that should cover this.
