### ISSUE TITLE
Create new model without declaring parameters 

### ISSUE THREAD

**Issue by wangwillian0** [SciML/Catalyst.jl#333]
It would be nice if the macro `@reaction_network` could infer the parameters and the chemical species directly from the model without the need to declare the parameters after `end`.

**Comment by isaacsas** [comment]
This is tricky because we might want to ultimately allow
```julia
rn = @reaction_network begin
              k*B, 3*A  --> 2*C
       end k
rn2 = @reaction_network begin
              k, 3*A  + 2*B --> 2*C
       end k B
```
to default `B` to be a species in the former and a parameter in the latter. This could be useful in defining composed networks from smaller sub-networks, but requires some way of the user telling us what is a species vs. parameter.

**Comment by TorkelE** [comment]
One thing we could potentially do, unless we find something which covers all cases, is to allow for different macros, e.g.
```julia
rn = @sometag_reaction_network
    (k1,k2), X1 <-->X2
end
```
which then know that all species are declared as reaction components.

**Comment by wilwxk** [comment]
I see... But even if its not the most common, does changing to declaration of species instead of parameters solve part of this issue ? There is no reaction without reactant (is even possible to create a model with parameters only ?). Maybe make the current macro work with declaration of species while infer automatically when nothing is declared - so it cover every strange model and just works; and create a new macro to deal with more customization like the order of parameters (and species too if its possible) ?

**Comment by TorkelE** [comment]
Declaring with species instead of parameters would work. But there's still teh question what woudl actually be the most useful default (i.e. do more people prefer declaring the paraemter order or not). So some kind of decision would have to be made, personally, I'm not sure what I would prefer, and would have to think about it. Decisions can take time! This would also be a really breaking change, so would need to wait until a really major update anyway.

What I'm saying is that changing the default to what you suggest would take time, and the by far quickest solution would be to make an alternative macro, from there it would also be easier for people to figure out what they'd prefer as the default behaviour.

**Comment by wilwxk** [comment]
Got it, personally I like more to order the species because usually my parameters are just constants while I need to manipulate and plot the species, but I understand your point. I will try to keep track of it 🙂

**Comment by isaacsas** [comment]
We should just make the DSL consistent with what `@reaction` does. Adding parameters at the end can be an optional way to overrule this default.

**Comment by isaacsas** [comment]
This is now on master and will be in Catalyst 13
