### ISSUE TITLE
Changes to parameter orders

### ISSUE THREAD

**Issue by kaandocal** [SciML/Catalyst.jl#453]
It seems like the last update changed the order of parameters in a reaction network, at least in some that we were considering. I am not entirely sure about the reasons behind this, but looking at the release log I would strongly recommend marking such changes as "breaking" in the future - code that runs with one version does not run correctly with another, and since this is a semantic error it does not result in a warning or an error...

**Comment by isaacsas** [comment]
Between which two versions was there a change? 10.2 only changed a dependency version, in a manner that shouldn't be breaking. We had a change with version 10.0, but did announce this in the HISTORY.md. We also announced there that going forward changing the ordering of species and parameters would not be considered breaking as these are not considered invariant by ModelingToolkit. 

My understanding, and @ChrisRackauckas can correct me if this is wrong, is that one should not assume immutable orderings for states or parameters between any versions. I believe one can assume that `states(sys)` and `parameters(sys)` will always define the current ordering for a given system, and we certainly assume that internally.

For parameter / initial condition specification ModelingToolkit really wants you to use parameter mappings (i.e. [A => 1.0, B => 2.0,...], which use `varmap_to_vars` internally to get a correctly ordered array of values. Alternatively, you can  specify default values when constructing the system. These currently use the orderings within `states(rn)` and `parameters(rn)`. 

If you have other reasons you need the ordering you can use `states(rn)` and `parameters(rn)` to figure it out. If you have a scalar system (no subsystems or constraint systems), `speciesmap(rn)` and `paramsmap(rn)` will return a dictionary mapping symbolic variable to their order in the system. 

For what reason do you need the orderings?

Note, I think master has a change that is closer to the pre-version 10.0 ordering, but we have not released that yet. It looks like I forgot to ask @TorkelE to make mention of this in the HISTORY.md as an unreleased change when we merged his PR. We can release this as a breaking change in V11, but generally we can't rely on ModelingToolkit functionality not changing the ordering too going forward...

**Comment by ChrisRackauckas** [comment]
> My understanding, and @ChrisRackauckas can correct me if this is wrong, is that one should not assume immutable orderings for states or parameters between any versions. I believe one can assume that states(sys) and parameters(sys) will always define the current ordering for a given system, and we certainly assume that internally.

Yes, it's even more than that. MTK is free to delete species if it can analytically reduce the system. It does this all of the time in the generated ODEs for example, so putting a vector in for the `u0` isn't a great idea since you might not even have the right number of variables! For example, if you have redundant connections they may just be deleted before solving and lazily reconstructed when you do `sol[x]`, so the symbolic initial condition handling will take care of the mappings there in a way that cannot ever be automated from just a `u0 = [0.5,0.2,0.3]` kind of thing. 

> Note, I think master has a change that is closer to the pre-version 10.0 ordering, but we have not released that yet. It looks like I forgot to ask @TorkelE to make mention of this in the HISTORY.md as an unreleased change when we merged his PR. We can release this as a breaking change in V11, but generally we can't rely on ModelingToolkit functionality not changing the ordering too going forward...

There were a few versions where it was effectively random. https://github.com/SciML/Catalyst.jl/pull/452 is at least the desired behavior, though I think with enough engineering the parameter list at the end of the macro (or the full macro itself) could effectively be deleted and replaced with:

```julia
rn = @reaction_network begin
       (p,d), 0 <--> X
end
```

or 

```julia
r1 = @reaction K*A, A --> B
ReactionSystem(r1,[A,B],[K])
```

I'm starting to lean pretty heavily towards the latter. But even that, that would give the user direct control over the ordering at the time of the definition of the system, but of course there's no reason to expect transformations to respect that same ordering because in principle that idea is ill-defined if a transformation is adding or deleting states and parameters, which is why the variable maps are the preferred way of doing it even if that form exists.

**Comment by TorkelE** [comment]
> Note, I think master has a change that is closer to the pre-version 10.0 ordering, but we have not released that yet. It looks like I forgot to ask @TorkelE to make mention of this in the HISTORY.md as an unreleased change when we merged his PR. We can release this as a breaking change in V11, but generally, we can't rely on ModelingToolkit functionality not changing the ordering too going forward...

That's a good point. Haven't really done any significant (any at all?) PRs since we added the history file and forgot it. is it possible to make the change now, or would that not make sense?

**Comment by isaacsas** [comment]
Yes, we can add it now if you want.

**Comment by isaacsas** [comment]
Closing since this seems resolved based on the discussion above and was reverted in 10.3.

**Comment by kaandocal** [comment]
Apologies for the late answer - the old, "inofficial" system with fixed ordering was quite convenient, especially for prototyping, but the discussion was very illuminating, particularly concerning the reasoning behind everything!

**Comment by isaacsas** [comment]
In any case the order should be back to what it was, and we'll try to keep as is if possible. I'm trying to make entering default values for initial conditions and parameters easier to handle for the next release, so hopefully that will help with this too.
