### ISSUE TITLE
Using strings to create reaction network pieces

### ISSUE THREAD

**Issue by Leticia-maria** [SciML/Catalyst.jl#472]
Hey you all, I wanna use Strings to add reactions to a ```@reaction_network``` in Catalyst.jl. For example:

```julia
julia> example = @reaction_network empty
julia> addreaction!(example, "k, A --> B")
```
or
```julia
julia> addreaction!(example, "A --> B")
```

Is there a way to convert these types?

**Comment by ChrisRackauckas** [comment]
`parse(str)`

**Comment by ChrisRackauckas** [comment]
Actually it looks like we'd have to implement a custom parser for that.

**Comment by Leticia-maria** [comment]
> Actually, it looks like we'd have to implement a custom parser for that.

Yes, that's what I guessed. Can I help to do it and submit a PR?

**Comment by isaacsas** [comment]
Why not just concatenate all the strings together and wrap with the macro?

**Comment by Leticia-maria** [comment]
Because it didn't work, @isaacsas. That's the point

**Comment by isaacsas** [comment]
```julia
str = "@reaction_network begin \n"
str *= "k, A --> B \n"
str *= "k2, B --> A \n"
str *= "end k k2"
ex = Meta.parse(str)
rn = eval(ex)
```

**Comment by Leticia-maria** [comment]
Based on your example, I've written a function that takes two arrays (constants & schemes) and returns the @reaction_network model:

```julia
unction reaction_network(constants, schemes)
    reactions = String[]

    for (constant, scheme) in zip(constants, schemes)
        push!(reactions, constant*", "*scheme*" \n")
    end 

    network = "@reaction_network begin \n"

    for reaction in reactions
        network *= reaction
    end

    complete_network = network*"end "

    for constant in constants
        complete_network *= constant*" "
    end

    parsed_network = Meta.parse(complete_network)

    rn = eval(parsed_network)    

    return rn
end
```

**Comment by Leticia-maria** [comment]
But I think we still need a parser that enable @reaction_network to receive string as args. Don't you agree?

**Comment by ChrisRackauckas** [comment]
ahh yeah `Meta.parse`

You almost certainly don't want to do this though. Using the macro directly, or a string macro, will work in context and not in the global scope (which eval) needs. So this is is slow and brittle. I wouldn't keep going in that direction.

**Comment by Leticia-maria** [comment]
So, @ChrisRackauckas and @isaacsas. Could I create a dedicated parser to do it and submit as a PR? You can assign me to the this issue and put a deadline of 1 or 2 weeks.

**Comment by isaacsas** [comment]
If you want to make the current expression parser more modular and/or add a simple wrapping macro that takes a string, converts it to an expression with `Meta.parse`, and then uses the current parser that would be great. For ease of maintenance going forward I think this should be the general approach to handling strings (i.e. not writing a whole new separate string-based parser).

**Comment by ChrisRackauckas** [comment]
I don't think we should support strings. Is there any reasonable use case? I can't think of one.

**Comment by isaacsas** [comment]
I can’t see a use case beyond interfacing with a gui or some file format, but in both those cases converting to expressions should work right? I’ll try to get an

```julia
@reaction k, A —> B
```

macro soon, which should handle incremental construction. I just haven’t had a chance to look through the current parser code and figure out how to modify it to handle already-defined symbols properly (since we’d want this to reuse `A` if it’s defined, or else create a new sym with that name). Macro stuff always takes me a while since I only seem to write them for the Catalyst DSL…

**Comment by isaacsas** [comment]
@Leticia-maria can you explain a bit more about why you want to use strings? I just added a macro that let's you do 
```julia
rx = @reaction k, A --> B
```
so maybe that fixes the issue you are having? 

I'm going to close this for now, since I think we've given you a couple options, and we don't really want to add a second parser that works directly on strings (since that would be a whole new set of code to maintain).
