### ISSUE TITLE
Parametric non-integer stoichiometry

### ISSUE THREAD

**Issue by MichielStock** [SciML/Catalyst.jl#481]
I love the package and would like to use them beyond chemical modelling. We are looking to implement a Lotka-Volterra like growth of a bacteria-phage system:

```julia
sys = @reaction_network begin
    α, B --> 2B  # bacterial growth
    α*B/K, B --> 0  # bacterial death
    β, P + B --> b * P  # infection
    d, P --> 0  # phage decay
end α β K d b
```

So, the third reaction is an infection of a bacteria (B) with a phage (P) resulting in `b` new phages (the burst size). It does not seem to be supported to add `b` as a parameter (not even using `$` for string interpolation). Furthermore, `b` might be non-integer.

The SIR example in the docs hints that Catalyst might serve outside the domain of (bio)chemistry. Mass-action kinetics also occurs in e.g. ecology. Is my use of parametric stoichiometry supported or should I look for using this in the more general `ModelingToolkit`?

**Comment by isaacsas** [comment]
Is `b` just a fixed number? We don't currently support this, but that is a case I think we could add in a relatively straightforward manner. 

We've had this on the TODO for a while, but one of the goals was to let `b` be a random variable, which I didn't know how to properly manage with the way Symbolics.jl builds the resulting ODE functions.

**Comment by MichielStock** [comment]
`b` is initially fixed. If it is defined outside, you might include it using string interpolation `$`.

The more pressing issue is allowing floats for stoichiometric coefficients. This makes less sense for pure chemistry, but would be super useful for many biology applications such as, e.g. fermentation:
```
ecoli + glucose-> 0.3ecoli+1.2ethanol
```
or similar stuff. 

The coefficients might also change (switching metabolism) so `b` could be a function depending on internal or external parameters. 

The latter is likely harder to encode, but the former would IMO greatly enhance the scope of the package.

**Comment by isaacsas** [comment]
Yeah, this should work if you build `Reaction`s directly, but we call `factorial` when building the ODEs by default, so need to tweak that. 

I think just getting floats to work too shouldn't be too bad, so I'll look into it.

**Comment by isaacsas** [comment]
@MichielStock see https://github.com/SciML/Catalyst.jl/pull/482 for floating point stoichiometry. They should hopefully work now, but please do let us know if there are issues. Right now you have to explicitly set `combinatoric_ratelaws=false` when calling `ODEProblem` or `convert` as the rate constant scaling we use will cause errors with the floating point stoichiometry. The docs explain how this keyword relates to the underlying ratelaw we use.

Parametric will be a bit more work still.

**Comment by MichielStock** [comment]
Seems to work well, thanks!

Maybe now it would also make sense to have the stoichiometric as a variable? For simplicity, it can be a non-parameter, but user-defined using string interpolation:

 ```julia
p = 1.2

rn = @reaction_network begin
         k, 2.5*A --> $b*B
       end k
end
```

**Comment by isaacsas** [comment]
That is the plan to do next. 

For now I'd suggest you do
```julia
p = 1.2
rx = Reaction(k, [A], [B], [2.5], [p])
...
```

**Comment by isaacsas** [comment]
@MichielStock https://github.com/SciML/Catalyst.jl/pull/488 adds parametric stoichiometry via directly building `Reaction(...)`s. So you can now use that once it merges (i.e. use the DSL for non-parametric reactions and just extend/add on the extra parametric reactions to the already built system -- making sure to also add on any new species or parameters).

The one caveat is that ModelingToolkit upconverts all parameters from integer to floating point if you pass a tuple of mixed types for the initial condition mapping. This then causes an error with factorial functions in the default rate law form. You can either use `osys = convert(ODESystem, rn; combinatoric_ratelaws=false)` or `ODEProblem(rn, ...; combinatoric_ratelaws=false)` to disable our rescaling of rate laws by these factors (which should avoid the issue for ODE systems). Alternatively, you can pass a tuple with just numbers for the parameters to `ODEProblem`, which bypasses ModelingToolkit looking at it (i.e. don't do `(:A => 1.0, :n => 1)` but do `(1.0,1)` consistent with the ordering reported by `parameters(rn)`). I'll add some examples in the HISTORY.md file once the PR gets merged.

I'm going to close this as I've got a new issue on getting this to work in the DSL too (which may take a while longer since it will entail a decent amount of changing around macro parsing code I think).
