### ISSUE TITLE
Non-unicode alternative for overriding mass action kinetics

### ISSUE THREAD

**Issue by gaurav-arya** [SciML/Catalyst.jl#574]
The documentation at [https://docs.sciml.ai/Catalyst/dev/faqs/#How-to-override-mass-action-kinetics-rate-laws?](https://docs.sciml.ai/Catalyst/dev/faqs/#How-to-override-mass-action-kinetics-rate-laws?) seems to suggest that the only way to disable the mass action kinetics law is to use unicode non-filled arrows, but this seems to violate the SciML code style (https://github.com/SciML/SciMLStyle) which states "Unicode is fine within code where it increases legibility, but in no case should Unicode be used in public APIs.". Could there be a non-unicode alternative for this?

**Comment by TorkelE** [comment]
To be honest, I am not sure if there are some standard, non-unicode, arrows that could be used to represent this.

Is this feature actually used extensively? 

I agree that it would be good to fix though.

**Comment by ChrisRackauckas** [comment]
We could use something like `=>`?

**Comment by TorkelE** [comment]
It would require some slight tinkering as e.g.
```julia
ex1 = :(k1, X => Y)
ex2 = :(k1, X --> Y)
```
are different kinds of expression 
(`X => Y` is a call with 3 args, while `X --> Y` is a "`-->`" with 2 args)

It should be very doable though, and make sense since `=>` looks a bit like the arrows we already use for the purpose. I will add it to the list of stuff to do.

**Comment by TorkelE** [comment]
Fixed in by https://github.com/SciML/Catalyst.jl/pull/580#issuecomment-1397505454
